### ISSUE TITLE
Breaks Rails 5.1

### ISSUE THREAD

**Issue by pawelkomarnicki** [codenize-tools/gratan#20]
For Rails 5.1.6 the gem breaks rails itself:

```Running via Spring preloader in process 8180
rails aborted!
Don't know how to build task 'console' (see --tasks)
/Users/pawel/Sites/gratan-test/bin/rails:9:in `<top (required)>'
-e:1:in `<main>'
(See full trace by running task with --trace)
```

with --trace:

```Running via Spring preloader in process 8208
rails aborted!
Don't know how to build task 'console' (see --tasks)
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/Users/pawel/Sites/gratan-test/bin/rails:9:in `<top (required)>'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/pawel/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
```

**Comment by winebarrel** [comment]
It does not seem to be gratan's problem.
